trigger:
- master
- test

variables:
- group: devsu-app

stages:
- template: '.devops/plantillas/ci-cd/stages/cicd-stages.yaml'
  parameters:
    agent: 'pruebas'
    nodeVersion: 18
    sonarSc: $(sonarSc)
    dockerSc: $(dockerSc)
    containerRepository: $(containerRepository)
    k8sSc: $(k8sSc)
    pathToManifest: './devops/kubernetes/deploys.yaml'