apiVersion: v1
kind: PersistentVolume
metadata:
  name: devsu-app-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devsu-app-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: devsu-app-secrets
  namespace: default
type: Opaque
data:
  database_user: __user-db__
  database_password: __user-pass__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-app-config
  namespace: default
data:
  DATABASE_NAME: "/app/dev.sqlite"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-app
  template:
    metadata:
      labels:
        app: devsu-app
    spec:
      containers:
        - name: devsu-app
          image: __containerRepository__:__build.BuilId__
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: devsu-app-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: devsu-app-secrets
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devsu-app-secrets
                  key: database_password
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /app
              name: devsu-app-storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ln -sf /data/dev.sqlite /app/dev.sqlite"]
      volumes:
        - name: devsu-app-storage
          persistentVolumeClaim:
            claimName: devsu-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devsu-app
  namespace: default
spec:
  selector:
    app: devsu-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsu-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devsu-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50